baseURL = 'https://jamesatk.in/blog/'
languageCode = 'en-gb'
title = 'jamesatk.in'
theme = 'diary'
# canonifyURLs = true

[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1

# [[menu.main]]
# url = "/tags"
# name = "Tags"
# weight = 3

# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 4


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'xcode-dark'
tabWidth = 2


[params]
favicon = "https://raw.githubusercontent.com/jamesalexatkin/jamesalexatkin.github.io/master/favicon.png"
# enableReadingTime=true
# custom_css = ["css/custom_style.css"]
